#!/usr/bin/env python3
"""Sync all public GitHub repos from both accounts into src/data/projects.ts.

Usage:  python3 scripts/sync-repos.py
Re-run anytime to pick up new repos or updated descriptions.
"""
import base64
import json
import re
import urllib.request
from pathlib import Path

USERS = ["amitb-gpu", "amitb-quantum"]
# Repos that are infrastructure for the site itself, not showcase projects.
EXCLUDED = {"amit-brahmbhatt.dev"}
FEATURED = {
    "gada-gpu-analytics",
    "gpu-fit",
    "cachelens",
    "entangl",
    "proofgate-pq",
    "decisiongate",
}
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "data" / "projects.ts"
OVERRIDES = ROOT / "src" / "data" / "descriptions.override.json"


def load_overrides():
    """Curated 2-3 sentence descriptions, keyed by 'org/repo'. Preferred over
    GitHub descriptions so hand-written copy survives re-syncs."""
    if OVERRIDES.exists():
        return json.loads(OVERRIDES.read_text())
    return {}


def api(path):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={
            "User-Agent": "amit-site-sync",
            "Accept": "application/vnd.github+json",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def readme_first_line(owner, repo):
    """First meaningful line of the README, for repos with no description."""
    try:
        data = api(f"/repos/{owner}/{repo}/readme")
        text = base64.b64decode(data["content"]).decode("utf-8", "replace")
        for line in text.splitlines():
            s = line.strip()
            if not s or s.startswith(("#", "![", "[![", "<", "|", "-", "* ")):
                continue
            s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)  # [text](url) -> text
            s = re.sub(r"[*_`>]", "", s).strip()
            if len(s) > 25:
                return s[:220]
    except Exception:
        pass
    return ""


def ts_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    overrides = load_overrides()
    entries = []
    for user in USERS:
        repos = api(f"/users/{user}/repos?per_page=100&type=public&sort=updated")
        for r in repos:
            if r.get("fork"):
                continue
            if r["name"] in EXCLUDED:
                continue
            key = f"{user}/{r['name']}"
            desc = overrides.get(key, "").strip()
            if not desc:
                desc = (r.get("description") or "").strip()
            if not desc:
                desc = readme_first_line(user, r["name"])
            if not desc:
                desc = "No description yet — see the repo for details."
            tags = [t for t in (r.get("topics") or [])[:3]]
            if r.get("language") and len(tags) < 4:
                tags.append(r["language"])
            featured = "true" if r["name"] in FEATURED else "false"
            tags_ts = ", ".join(f'"{ts_escape(t)}"' for t in tags)
            entries.append(
                f"""  {{
    name: "{ts_escape(r["name"])}",
    description: "{ts_escape(desc)}",
    url: "{r["html_url"]}",
    tags: [{tags_ts}],
    org: "{user}",
    featured: {featured},
  }},"""
            )

    body = "\n".join(entries)
    OUT.write_text(
        """export interface Project {
  name: string;
  description: string;
  url: string;
  tags: string[];
  org: "amitb-gpu" | "amitb-quantum";
  featured?: boolean;
}

// Auto-generated by scripts/sync-repos.py — re-run to sync with GitHub.
// Featured flags are preserved in the FEATURED set inside the script.
// Curated descriptions live in src/data/descriptions.override.json and win over GitHub.
export const projects: Project[] = [
"""
        + body
        + "\n];\n"
    )
    print(f"Wrote {len(entries)} repos to {OUT}")


if __name__ == "__main__":
    main()
